### ISSUE TITLE
TBMsg::getConversationMessages($conv_id, $user_id);

### ISSUE THREAD

**Issue by goranata** [tzookb/tbmsg#28]
Hi, I've just chosen you package, after comparing with the existing for a messaging system on my website, and I have installed it via composer.

I have a little issue here and I cannot get all of message from a certain conversation, using this: conv = TBMsg::getConversationMessages('1', $user->id); // i've set the id=1, for a demo, while I'm developing this module.

The only thing I get is the last inserted message from a conversation, instead of listing default order by DESC all of them, for the $conv_id provided.

Could be please help ?

**Comment by tzookb** [comment]
Le t me check on that

**Comment by RaoulDijksman** [comment]
This is what i have and works great:
```PHP
$conv = TBMsg::getConversationMessages($convId, $userId);
$conv = $conv->getAllMessages();
```

Try using the getAllMessages() funtion on the conversation object.

Raoul

**Comment by goranata** [comment]
Heres the code in my view, according the examples:

foreach ( $conv->getAllMessages() as $msg ) {
						
						$senderId = $msg->getSender();
						$content = $msg->getContent();
						$status = $msg->getStatus();
						$created_at = $msg->getCreated();

echo '....';

}

![toobz](https://cloud.githubusercontent.com/assets/6684817/5606131/8fcaceec-941f-11e4-9f4f-d8cf5d946e95.jpg)

**Comment by RaoulDijksman** [comment]
How did you build the conversation object?

**Comment by goranata** [comment]
$conv = TBMsg::getConversationMessages('1', $user->id); // Controller
I pointed the static id of 1 in this case.

**Comment by RaoulDijksman** [comment]
Mmm i don't see why that's isn't working... Did you try a few var_dumps() to debug the objects and variables your using?

**Comment by goranata** [comment]
Here's what I get:

object(Tzookb\TBMsg\Entities\Message)#548 (6) { ["id":protected]=> int(5) ["sender":protected]=> int(1) ["status":protected]=> int(1) ["self":protected]=> int(1) ["content":protected]=> string(21) "Ne be ti si glpo dete" ["created":protected]=> string(19) "2015-01-04 05:00:28" }

One message again.

**Comment by tzookb** [comment]
that looks weird... what version of the package you have?
can you please find the function:
    
    getConversationMessages

and paste here the code of it, so I could know the version.

In your DB all looks good...

**Comment by goranata** [comment]
this is in my composer:
"tzookb/tbmsg": "1.0.*" I followed all the installation steps, I checked if I require publish config files, saw that there are only table and primary ID's which were correct and enough.


location: /vendor\tzookb\tbmsg\src\Tzookb\TBMsg\TBMsg.php
public function getConversationMessages($conv_id, $user_id, $newToOld=true) {
        if ( $newToOld )
            $orderBy = 'desc';
        else
            $orderBy = 'asc';
        $results = DB::select(
            '
            SELECT msg.id as msgId, msg.content, msg.created_at, us.'.$this->usersTableKey.' as userId
            FROM messages_status mst
            INNER JOIN messages msg
            ON mst.msg_id=msg.id
            INNER JOIN '.$this->usersTable.' us
            ON msg.sender_id=us.'.$this->usersTableKey.'
            WHERE msg.conv_id=?
            AND mst.user_id = ?
            AND mst.status NOT IN (?,?)
            ORDER BY msg.created_at '.$orderBy.'
            '
            , array($conv_id, $user_id, self::DELETED, self::ARCHIVED));

        $conversation = new Conversation();
        foreach ( $results as $row )
        {
            $msg = new Message();
            $msg->setId( $row->msgId );
            $msg->setContent( $row->content );
            $msg->setCreated( $row->created_at );
            $msg->setSender( $row->userId );
            $conversation->addMessage( $msg );
        }

        $usersInConv = $this->getUsersInConversation($conv_id);
        foreach ( $usersInConv as $userInConv )
            $conversation->addParticipant( $userInConv );


        return $conversation;
    }

**Comment by RaoulDijksman** [comment]
Try using the dev-master version. 

```
"tzookb/tbmsg": "dev-master"
```

**Comment by goranata** [comment]
Apparently everything seems the be OK with Your package.

I was using the same variable $conv in both queries
<?php foreach ( $convs as $conv ) { // for displaying all the user conversations on the left (col-md-3)

					
foreach ( $conv->getAllMessages() as $msg ) { // for displaying messages for the selected conversation (col-md-9).

Changed these and everything is fine. 
Thank You for the time.
I will send you an email, when I'll finish this chat messaging system, so you can see it.
