### ISSUE TITLE
TBMsg 1.1 not compatible with laravel 4.2

### ISSUE THREAD

**Issue by RaoulDijksman** [tzookb/tbmsg#30]
Hi,
I would like to report that TBMsg 1.1 isn't compatible with laravel 4.2.
This is because the new version makes use of the packages ```illuminate/database``` version 5.0.
Are new versions of TBMsg only compatible with laravel 5.0?

Raoul

**Comment by tzookb** [comment]
thanks for that, I went ahead with myself
