### ISSUE TITLE
Conversation subject

### ISSUE THREAD

**Issue by lostcause** [tzookb/tbmsg#31]
I couldn't find anything about this: is there a way to add a subject to each conversation?

**Comment by tzookb** [comment]
Currently there is no subject but i noticed many people request for it so ill add it

**Comment by vegadaniel** [comment]
Hello Tzookb, thanks a lot for this package, I'm trying to implement it in my app.
Can you please help me with a basic explanation on what could be the best way to add subject or another fields to a message, without damage the rest of the package?
Thanks in advance for your help.
Best Wishes,

**Comment by tzookb** [comment]
Hi Daniel,  are using l4 or l5?
Ill add a subject after the migrate to l5

**Comment by RaoulDijksman** [comment]
Hey vegadaniel,

I would recomand waiting for Tzookb. If you need it now i would recommand making a new table called conversation_subject with the colums: ID, conv_id, subject. In your model you can then make an relationship with the conversations table.

Raoul

**Comment by tzookb** [comment]
just started doing this, it is on branch "conv_title"

**Comment by RaoulDijksman** [comment]
I would like to recommend that the title remains optional.

**Comment by tzookb** [comment]
it will of course

**Comment by tzookb** [comment]
Hi Raul,
version 3 (branch v3)
that Im working now will contain optional titles.
