### ISSUE TITLE
TBMsg::createConversation not creating corresponding entries in conv_users table

### ISSUE THREAD

**Issue by tmunzar-jfish** [tzookb/tbmsg#39]
The package used to work perfectly, until I reset my database and switched from MySQL to Postgres.

The TBMsg::createConversation doesn't work as it should anymore.

It creates an entry in the conversations table, but it fails to make any corresponding entries in the conv_users table.

Here's the relevant code:

 if ($validator->passes()) {
        	$conv = TBMsg::getConversationByTwoUsers($user_id, $recepient_id);
			if($conv < 0) {
				$conv = TBMsg::createConversation([$user_id, $recepient_id]);
				$conv = $conv->id;
			}
				$to_conv = TBMsg::addMessageToConversation($conv, $user_id, $content); //this is where it fails because it can't find the user in the conversation.
				return Redirect::route('messages.index');
        }

**Comment by tmunzar-jfish** [comment]
To reconfirm, I reverted to MySQL and the code worked perfectly fine there.

The bug is happening on postgres 9.4, if that helps.

**Comment by tzookb** [comment]
Yes it is probably the column select alias,  I will install postures and fix it sson

**Comment by tzookb** [comment]
did you had success with this, do you where is the problem with the aliases?
