### ISSUE TITLE
1.1.* branch needs an update

### ISSUE THREAD

**Issue by RaoulDijksman** [tzookb/tbmsg#40]
Hey,

I just found that the 1.1.1 release uses an old commit. The 1.1 branch needs an update to commit 0467f651c31471dcdbb5c736dc0aed41b24e476b to contain all the last commits for laravel 4.2. Could you make a 1.1.2 release?

Raoul

**Comment by RaoulDijksman** [comment]
I took a look at your code, and everything such still run on laravel 4.2. Are you planning on adding laravel 5.0 only features? If not your can just tell composer to accept both 4.* and 5.* versions like this:
```
"illuminate/contracts": "~4.2|~5.0",
"illuminate/database": "~4.2|~5.0"
```
And dev options to:
```
"illuminate/filesystem": "~4.2|~5.0",
```

**Comment by tzookb** [comment]
what do you mean?

now version 5 is supported with tbmsg version 2....

**Comment by RaoulDijksman** [comment]
I mean that the latest release in the 1.1.x branch, for laravel 4, is 1.1.1 which is on commit d91d4ad1c69e0baef2021b180b476debdf820cad, thats from Jan 10. 
You made alot of commit after that, up to 0467f651c31471dcdbb5c736dc0aed41b24e476b, Jan 17. I need these changes but there is no way i can get them from composer on laravel 4. Not even with `dev-master#0467f651c31471dcdbb5c736dc0aed41b24e476b`  becuase composer looks at the laatste composer.json and sees the 5.0.* requirement.
Clue of the story, could you make a 1.1.2 release on the 0467f651c31471dcdbb5c736dc0aed41b24e476b commit. That way laravel 4 projects can get a working copy of TBMsg.

-------

I also wanted to let you know that you dont need to hardcode 1 version in the composer.json file. You can support both version of the package with: 
```
"illuminate/contracts": "~4.2|~5.0",
"illuminate/database": "~4.2|~5.0"
```
And dev options to:
```
"illuminate/filesystem": "~4.2|~5.0",
```
This ofc only works if you are not planning on using feauters that are Laravel 5 only in the code. But up till now you haven't.

**Comment by tzookb** [comment]
thanks for the info about supporting 2 version in same time, but there are small changes in the code depending on the version.
For what you said about the commits and versions Ill try to check what you mean

**Comment by RaoulDijksman** [comment]
Thanks @tzookb,

If you need any more info, let me know. You should be able to do this in 5min.

**Comment by tzookb** [comment]
Im sorry, please tell me what exactly I need to do

**Comment by RaoulDijksman** [comment]
If you go to your releases: https://github.com/tzookb/tbmsg/releases
you will see that the 1.1.1 is commit d91d4ad1c69e0baef2021b180b476debdf820cad, thats from Jan 10. 
**Can you make a 1.1.2 on commit 0467f651c31471dcdbb5c736dc0aed41b24e476b, that's on Jan 17?** This will allow me to use the last commits voor laravel 4.

**Comment by RaoulDijksman** [comment]
Could you look at this? I can't use this package at the moment for my laravel 4 projects. :s 
You only need to make a release in github, should be done in 1 min. 
If you go to https://github.com/tzookb/tbmsg/releases/tag/v1.1.1 you can see that it says `16 commits to master since this tag`, 8 of these commits are for laravel 4 that are needed.

**Comment by tzookb** [comment]
Im sorry just got back to the world, is this solved?

**Comment by RaoulDijksman** [comment]
I can confirm this is still an issue on Laravel 4.x. But I moved all my projects to laravel 5.x but i'm not having any problems atm.

**Comment by tzookb** [comment]
thanks Raul,

working on version 3, to be well built tnx!
