### ISSUE TITLE
Unnecessary var_dump() in ServiceProvider

### ISSUE THREAD

**Issue by ahmadmmughal** [tzookb/tbmsg#44]
There is an unnecessary var_dump($usersTable) line in the TBMsgServiceProvider : register() function that breaks up the view when rendered..

**Comment by tzookb** [comment]
are you in the latest version? commit?

**Comment by ahmadmmughal** [comment]
I added this to my composer: "tzookb/tbmsg": "2". So i guess version i am on version 2?

**Comment by goranata** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/6684817/9285100/84f61360-42e2-11e5-86f3-9ae5fa48e9e6.jpg)
here's what I'm getting after adding it, to app.php

**Comment by rohitnaidu19** [comment]
im also getting this issue. Every time I do composer update the changes var_dump pops up. Can you comment it?

**Comment by tzookb** [comment]
ok I quickly removed that, can you please update to latest version and tell me if all is good?

**Comment by rohitnaidu19** [comment]
That was Quick! Thanks man :-) 
you saved me a Fork

**Comment by tzookb** [comment]
Hhhh no need forking for one line :)

**Comment by goranata** [comment]
This issue is still active ... pleae re-check ...
