### ISSUE TITLE
Dumps information about users table name

### ISSUE THREAD

**Issue by moharrum** [tzookb/tbmsg#46]
Hi,

It seems like in Tzookb\TBMsg\TBMsgServiceProvider at line 39 you forgot a var_dump:

```
var_dump($usersTable);
```

Edit (forgot to include version): 

tzookb/tbmsg (v 2.0.0)

**Comment by tzookb** [comment]
thanks, already fixed it. Just update your composer.json file to

     tzookb/tbmsg: 2.1.*

and update, it will get the latest...

**Comment by moharrum** [comment]
I guess you meant:

```
tzookb/tbmsg: 2.0.*
```

Thanks for the great package :+1:
