### ISSUE TITLE
Eh, doesn't seem to work...

### ISSUE THREAD

**Issue by ScooterSam** [tzookb/tbmsg#47]
There's no examples on using this. What exactly am I supposed to do? I followed the tests examples, and no luck there. Try to just create a convo between two users, like shown in the examples you have an I get.. "Non-static method Tzookb\TBMsg\TBMsg::createConversation() should not be called statically, assuming $this from incompatible context"

I'm so annoyed D: I cannot fathom why it wont work...

**Comment by tzookb** [comment]
sorry for the late response, but Im just building the new much better version,
what you had may be that you didn't register the facad.

If it is still relevant please show me the code.

**Comment by ScooterSam** [comment]
Yeah dude, I'd love to have it when it's finished. Will come in handy in lots of my projects :)
