### ISSUE TITLE
Return id of last message inserted

### ISSUE THREAD

**Issue by rohitnaidu19** [tzookb/tbmsg#48]
Can we get the the id of the message that was added to a conversation? currently i do the following to add a message:

$conv = TBMsg::sendMessageBetweenTwoUsers($user->id, $toUser->id, $request->content);

this returns the following object:
array:4 [
  "senderId" => 11
  "convUsersIds" => array:2 [
    0 => 9
    1 => 11
  ]
  "content" => "asdf asd asd arwtwrget hrth,reth htrhwsrthwrt"
  "convId" => 1
]

the inserted message id should also be returned. How can i do this?

**Comment by tzookb** [comment]
thanks for the feedback, working on version 3, and it will surely be supported.
